name: Dependabot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pub:
    name: Dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Update
        uses: IchordeDionysos/dependabot-pub-runner@main
        # with:
        # path: /examples/hosted
