name: Flutter

on:
  push:
    paths:
      - "**.dart"
  pull_request:
    paths:
      - "**.dart"
jobs:
  analyzer:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.1"
      - run: flutter pub get
      - run: flutter analyze
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.1"
      - run: flutter pub get
      - run: flutter test
  build_ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.1"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign -t lib/main_prod.dart
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.1"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk -t lib/main_prod.dart
      - run: flutter build appbundle -t lib/main_prod.dart
